INSERT INTO orders(user_id, net_cost) VALUES ('12','0.99');
INSERT INTO orders(user_id, net_cost) VALUES ('59','11.97');
INSERT INTO orders(user_id, net_cost) VALUES ('61','1.98');
INSERT INTO orders(user_id, net_cost) VALUES ('31','11.97');
INSERT INTO orders(user_id, net_cost) VALUES ('33','0.99');
INSERT INTO orders(user_id, net_cost) VALUES ('22','21.96');
INSERT INTO orders(user_id, net_cost) VALUES ('51','21.96');
INSERT INTO orders(user_id, net_cost) VALUES ('69','3.96');
INSERT INTO orders(user_id, net_cost) VALUES ('86','30.96');
INSERT INTO orders(user_id, net_cost) VALUES ('39','0.99');
INSERT INTO orders(user_id, net_cost) VALUES ('31','0.99');
INSERT INTO orders(user_id, net_cost) VALUES ('3','0.99');
INSERT INTO orders(user_id, net_cost) VALUES ('2','0.99');
INSERT INTO orders(user_id, net_cost) VALUES ('11','12.96');
INSERT INTO orders(user_id, net_cost) VALUES ('72','1.98');
INSERT INTO orders(user_id, net_cost) VALUES ('97','10.98');
INSERT INTO orders(user_id, net_cost) VALUES ('10','1.98');
INSERT INTO orders(user_id, net_cost) VALUES ('69','0.99');
INSERT INTO orders(user_id, net_cost) VALUES ('24','1.98');
INSERT INTO orders(user_id, net_cost) VALUES ('19','1.98');
INSERT INTO orders(user_id, net_cost) VALUES ('40','0.99');
INSERT INTO orders(user_id, net_cost) VALUES ('36','0.99');
INSERT INTO orders(user_id, net_cost) VALUES ('19','0.99');
INSERT INTO orders(user_id, net_cost) VALUES ('71','1.98');
INSERT INTO orders(user_id, net_cost) VALUES ('79','12.96');
INSERT INTO orders(user_id, net_cost) VALUES ('25','0.99');
INSERT INTO orders(user_id, net_cost) VALUES ('25','10.98');
INSERT INTO orders(user_id, net_cost) VALUES ('72','1.98');
INSERT INTO orders(user_id, net_cost) VALUES ('16','10.98');
INSERT INTO orders(user_id, net_cost) VALUES ('59','13.95');
INSERT INTO orders(user_id, net_cost) VALUES ('45','22.95');
INSERT INTO orders(user_id, net_cost) VALUES ('59','31.95');
INSERT INTO orders(user_id, net_cost) VALUES ('92','2.97');
INSERT INTO orders(user_id, net_cost) VALUES ('81','12.96');
INSERT INTO orders(user_id, net_cost) VALUES ('13','11.97');
INSERT INTO orders(user_id, net_cost) VALUES ('41','1.98');
INSERT INTO orders(user_id, net_cost) VALUES ('50','5.94');
INSERT INTO orders(user_id, net_cost) VALUES ('21','11.97');
INSERT INTO orders(user_id, net_cost) VALUES ('44','0.99');
INSERT INTO orders(user_id, net_cost) VALUES ('2','2.97');
INSERT INTO orders(user_id, net_cost) VALUES ('51','1.98');
INSERT INTO orders(user_id, net_cost) VALUES ('3','10.98');
INSERT INTO orders(user_id, net_cost) VALUES ('23','3.96');
INSERT INTO orders(user_id, net_cost) VALUES ('86','31.95');
INSERT INTO orders(user_id, net_cost) VALUES ('99','2.97');
INSERT INTO orders(user_id, net_cost) VALUES ('1','11.97');
INSERT INTO orders(user_id, net_cost) VALUES ('30','0.99');
INSERT INTO orders(user_id, net_cost) VALUES ('100','10.98');
INSERT INTO orders(user_id, net_cost) VALUES ('41','3.96');
INSERT INTO orders(user_id, net_cost) VALUES ('38','11.97');

INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('1','13','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('2','58','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('3','79','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('4','40','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('5','90','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('6','134','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('7','72','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('8','76','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('9','41','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('10','82','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('11','39','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('12','47','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('13','128','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('14','26','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('15','89','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('16','98','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('17','3','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('18','98','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('19','101','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('20','13','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('21','79','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('22','88','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('23','113','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('24','4','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('25','35','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('26','90','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('27','54','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('28','69','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('29','118','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('30','112','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('31','133','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('32','54','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('33','34','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('34','135','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('35','40','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('36','103','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('37','69','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('38','8','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('39','127','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('40','112','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('41','64','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('42','61','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('43','83','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('44','136','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('45','66','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('46','64','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('47','123','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('48','131','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('49','31','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('50','68','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('38','87','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('31','36','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('33','34','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('36','110','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('31','43','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('37','58','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('30','56','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('8','23','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('34','44','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('25','14','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('25','60','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('46','116','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('2','66','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('43','106','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('50','138','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('8','102','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('49','91','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('49','42','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('35','6','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('34','115','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('30','70','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('6','120','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('32','27','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('20','56','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('3','94','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('28','72','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('43','96','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('4','125','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('41','20','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('40','16','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('15','47','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('14','6','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('7','127','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('45','48','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('14','96','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('37','43','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('17','35','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('44','4','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('49','53','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('45','13','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('37','67','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('43','11','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('37','22','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('24','79','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('40','28','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('8','92','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('19','39','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('33','59','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('37','86','0.99', 0);
INSERT INTO order_items(order_id, track_id, cost, cancelled) VALUES ('30','72','0.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('38','26','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('27','57','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('44','50','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('32','66','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('4','34','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('9','13','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('50','46','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('44','66','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('32','26','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('7','43','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('14','14','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('30','16','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('48','13','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('7','37','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('35','56','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('42','66','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('46','51','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('34','32','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('31','31','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('29','54','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('16','69','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('9','26','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('9','63','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('31','27','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('25','52','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('32','34','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('6','38','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('2','27','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('44','68','9.99', 0);
INSERT INTO order_items(order_id, album_id, cost, cancelled) VALUES ('6','41','9.99', 0);
